### ISSUE TITLE
GrapeSlate::Blueprint in documentation does not exist

### ISSUE THREAD

**Issue by dbastin** [connexio-labs/grape-slate#4]
The README document refers to ```GrapeSlate::Blueprint.new(APIClass).generate``` Ummm. I can't see this class anywhere. Clues?

**Comment by johnallen3d** [comment]
hmmm looks like a typo. I believe that is referring to the `#generate` method on `GrapeSlate::Document` which is inherrited from [`GrapeMarkdown::Document#generate`](https://github.com/connexio-labs/grape-markdown/blob/master/lib/grape-markdown/document.rb#L16).
